version: 2.1

orbs:
  haskell: haskell-works/haskell-build-2@dev:araga
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.1.0

executors:
  darwin:
    macos:
      xcode: 10.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: Darwin
          executor: darwin
          run-tests: false
          fail-incoherent-builds: false
          write-result-workspace: true
          workspace-dir: osx
          after-checkout:
            - restore_cache:
                keys:
                  - homebrew-itself-cache
            - run:
                name: Install GHC
                command: brew install jq md5sha1sum ghc cabal-install

            - save_cache:
                key: homebrew-itself-cache
                # I cache Homebrew itself, not the stuff that is installed with it
                # because brew update takes up to 4 minutes for some reason.
                paths: [/usr/local/Homebrew]

            - run:
                name: Install cabal-plan
                command: |
                  curl -L https://github.com/haskell-works/cabal-plan/releases/download/v0.5.0.0/cabal-plan_x86_osx.tar.gz -o cabal-plan_x86_osx.tar.gz
                  tar zxvf cabal-plan_x86_osx.tar.gz -C /usr/local/bin cabal-plan
                  rm cabal-plan_x86_osx.tar.gz

      - haskell/build:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          write-result-workspace: true
          workspace-dir: linux

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          source-env-file: ./build/project.env
          requires:
            - GHC 8.6.5
            - Darwin
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  source ./linux/project.env
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./linux/dist/ ./${BUILD_EXE_NAME}

                  source ./osx/project.env
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./osx/dist/ ./${BUILD_EXE_NAME}
          # filters:
          #   branches:
          #     only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
