jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: 'macOS-10.13'

  strategy:
    matrix:
      ghc-8.6.4:
        GHC_VER: "8.6.4"

  steps:

    - script: |
        curl https://raw.githubusercontent.com/haskell/ghcup/master/bootstrap-haskell -sSf | sh
        . "$HOME/.ghcup/env"
        echo '. $HOME/.ghcup/env' >> "$HOME/.bashrc"
      displayName: Install GHC Up

    - script: |
        export PATH=$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH
        ghcup install ${GHC_VER}
        ghcup set ${GHC_VER}
      displayName: Install GHC

    - script: |
        export PATH=$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH
        ghc --version && cabal --version
      displayName: Print GHC version

    - script: |
        export PATH=$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH
        cabal v2-update
      displayName: Run cabal update

    - script: |
        export PATH=$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH
        cabal v2-configure
      displayName: Configure project

    - script: |
        export PATH=$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH
        cabal v2-build -j4 +RTS -A32m -RTS --enable-tests --enable-benchmarks
      displayName: Build project

    - task: GithubRelease@0
      displayName: GitHub Release
      inputs:
        githubConnection: hw-release
        action: edit
        repositoryName: haskell-works/cabal-cache
        target: $(Build.SourceVersion)
        tagSource: manual
        tag: $(Build.BuildNumber)
