name: Binaries

defaults:
  run:
    shell: bash

on:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.8.4", "8.6.5"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v2
        name: Cache cabal store
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cache-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal-cache.cabal') }}-${{ github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal-cache.cabal') }}-

      - name: Shorten binary names
        run: |
          sed -i.bak -e 's/cabal-cache/cbc/g' \
                     -e 's/cabal_cache/cbc/g' \
                     -e 's/Paths_cabal_cache/Paths_cbc/g' \
                     cabal-cache.cabal
          find app src -name '*.hs' -type f \
                    -exec sed -i.bak -e 's/Paths_cabal_cache/Paths_cbc/g' {} +
          find app src -name '*.bak' -type f -exec rm {} +

      - name: Set some window specific things
        if: matrix.os == 'windows-latest'
        run: echo '::set-env name=EXE_EXT::.exe'

      - name: Set some linux specific things
        if: matrix.os == 'ubuntu-latest'
        run: echo '::set-env name=LINUX_CABAL_ARGS::--enable-executable-static --ghc-options=-split-sections'

      - name: Build
        # Try building it twice in case of flakey builds on Windows
        run: |
          cabal build -O2 --write-ghc-environment-files=ghc8.4.4+ $LINUX_CABAL_ARGS || \
          cabal build -O2 --write-ghc-environment-files=ghc8.4.4+ $LINUX_CABAL_ARGS -j1

      - name: Trigger possible releases
        run: |
          echo 1

      - name: Compress Binary
        id: compress_binary
        env:
          GHC_VER: ${{ matrix.ghc }}
        run: |
          HS_BIN=$(find dist-newstyle \( -name 'cbc' -o -name 'cbc.exe' \) -type f)
          test -f "$HS_BIN"
          NAME=cabal-cache-$GHC_VER
          cp $HS_BIN $NAME${{env.EXE_EXT}}
          if [[ "$OSTYPE" == "msys" ]]; then
            7z a $NAME.zip $NAME${{env.EXE_EXT}}
            echo ::set-output name=path::$NAME.zip
            echo ::set-output name=content_type::application/zip
            echo ::set-output name=extension::zip
          else
            strip $NAME
            gzip --best $NAME
            echo ::set-output name=path::$NAME.gz
            echo ::set-output name=content_type::application/gzip
            echo ::set-output name=extension::gz
          fi

      - name: Upload Release Binary
        if: "github.event_name == 'release'"
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compress_binary.outputs.path }}
          asset_name: cabal-cache-${{ runner.OS }}-${{ matrix.ghc }}${{env.EXE_EXT}}.${{ steps.compress_binary.outputs.extension }}
          asset_content_type: ${{ steps.compress_binary.outputs.content_type }}

      - uses: actions/upload-artifact@v2
        with:
          name: cabal-cache-${{ runner.OS }}-${{ matrix.ghc }}${{env.EXE_EXT}}.${{ steps.compress_binary.outputs.extension }}
          path: ${{ steps.compress_binary.outputs.path }}
